version: '3.3'

services:
  backend:
    build: backend
    restart: always
    expose:
      - 3000
    networks:
      - internal

  frontend:
    build: frontend
    restart: always
    ports:
      - 3000:3000
    networks:
      - internal

networks:
  internal:
