version: '3.3'

services:
  backend:
    build: backend
    restart: always
    # volumes:
    #   - ./backend/app/src:/app/src
    expose:
      - 3000
    networks:
      - internal
    env_file:
      - postgres.env

  frontend:
    build: frontend
    restart: always
    # volumes:
    #   - ./frontend/app/src:/app/src
    ports:
      - 3000:3000
    networks:
      - internal

  database:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - postgres.env
    volumes:
      - postgres:/var/lib/postgresql
    expose:
      - 5432
    networks:
      - internal

networks:
  internal:

volumes:
  postgres:
